version: "3.3"

services:
  postgres_django_graphene:
    image: postgres:13.5
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: bind
        source: ./postgres_django_graphene/
        target: /var/lib/postgresql/data/
    ports:
      - target: 5432
        published: 1301
        mode: host
